# Generated by Django 4.2.6 on 2023-10-25 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_status_set_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=5000)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='set',
            name='shape',
            field=models.CharField(choices=[('xs-square', 'Extra-Short Square'), ('s-square', 'Short Square'), ('m-square', 'Medium Square'), ('s-coffin', 'Short Coffin'), ('m-coffin', 'Medium Coffin'), ('s-round', 'Short Round'), ('m-round', 'Medium Round'), ('s-almond', 'Short Almond'), ('m-almond', 'Medium Almond'), ('m-stilleto', 'Medium Stiletto')], default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='set',
            name='sizes',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='set',
            name='description',
            field=models.TextField(max_length=5000),
        ),
        migrations.CreateModel(
            name='SetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_images', to='orders.set')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ExampleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='example_images', to='orders.tier')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='set',
            name='tier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='orders.tier'),
            preserve_default=False,
        ),
    ]
