# Generated by Django 4.2.6 on 2023-10-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_tier_alter_order_options_set_shape_set_sizes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='set',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tier',
            name='description',
            field=models.TextField(),
        ),
    ]
