# Generated by Django 4.2.6 on 2023-10-27 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status_alter_set_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='set',
            options={'ordering': ['-created']},
        ),
    ]
