# Generated by Django 4.2.6 on 2023-11-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_exampleimage_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampleimage',
            name='url',
            field=models.URLField(max_length=3000),
        ),
    ]
