# Generated by Django 4.2.7 on 2023-11-03 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_exampleimage_instagram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setimage',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='orders.set'),
        ),
    ]
