# Generated by Django 4.2.7 on 2023-11-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_exampleimage_instagram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='sizes',
        ),
        migrations.AddField(
            model_name='set',
            name='left_sizes',
            field=models.CharField(default=(1, 1, 1, 1, 1), max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='set',
            name='right_sizes',
            field=models.CharField(default=(2, 2, 2, 2, 2), max_length=254),
            preserve_default=False,
        ),
    ]
