# Generated by Django 4.2.7 on 2023-11-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='characters',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='set',
            name='charms',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
