# Generated by Django 4.2.7 on 2024-03-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_set_characters_set_charms'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampleimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='exampleimage',
            name='url',
            field=models.URLField(blank=True, max_length=3000, null=True),
        ),
    ]
